<?php
/*
 * Chronolabs XOOPS Chat Module - xALKY
 * 
 * You may not change or alter any portion of this comment or credits
 * of supporting developers from this source code or any supporting source code
 * which is considered copyrighted (c) material of the original comment or credit authors.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 
 * @copyright 		Chronolabs Cooperative http://labs.coop
 * @license 		General Software Licence (https://web.labs.coop/public/legal/general-software-license/10,3.html)
 * @package 		radioo
 * @since 			1.111
 * @author 			Antony Cipher <cipher@labs.coop>
 * @author 			Simon Roberts <meshy@labs.coop>
 * @subpackage		kernel
 * @description		Chronolabs XOOPS Module for Chat and Walky Talky Services
 * 
 */
 

$modversion = array();
$modversion['name'] = _RADIOO_MI_MODULE_NAME;
$modversion['version'] = _RADIOO_MI_MODULE_VERSION;
$modversion['description'] = _RADIOO_MI_MODULE_DESCRIPTION;
$modversion['author'] = _RADIOO_MI_MODULE_AUTHOR;
$modversion['credits'] = _RADIOO_MI_MODULE_CREDITS;
$modversion['help'] = 'page=help';
$modversion['license'] = 'Chronolabs GSL';
$modversion['license_url'] = "web.labs.coop/public/legal/general-software-license/10,3.html";
$modversion['image'] = "image/mlogo_radioo.png";
$modversion['dirname'] = "radioo";
$modversion['dirmoduleadmin'] = '/Frameworks/moduleclasses/moduleadmin';
$modversion['icons16'] = 'images/icons/16';
$modversion['icons32'] = 'images/icons/32';

//about
$modversion["module_status"] = "rc-trial";
$modversion['release_date'] = '2014/10/20';
$modversion["module_website_url"] = "http://labs.coop/";
$modversion["module_website_name"] = "Chronolabs Cooperative";
$modversion['min_php'] = '5.3.7';
$modversion['min_xoops'] = "2.5.7";
$modversion['min_admin'] = '1.1';
$modversion['min_db'] = array(
 'mysql' => '5.0.7',
 'mysqli' => '5.0.7'
);

// Admin menu
// Set to 1 if you want to display menu generated by system module
$modversion['system_menu'] = 1;

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/RadiooDashboard.php";
$modversion['adminmenu'] = "admin/RadiooMenu.php";

// Mysql file
$modversion['sqlfile']['mysql'] = "sql/RadiooMySQL.sql";

// Table
$modversion['tables'][count($modversion['tables'])+1] = "radioo_iostores";
$modversion['tables'][count($modversion['tables'])+1] = "radioo_playlist";
$modversion['tables'][count($modversion['tables'])+1] = "radioo_genres";
$modversion['tables'][count($modversion['tables'])+1] = "radioo_authkeys";
$modversion['tables'][count($modversion['tables'])+1] = "radioo_schedules";

// Scripts to run upon installation or update
$modversion['onInstall'] = "include/RadiooInstall.php";
$modversion['onUpdate'] = "include/RadiooUpdate.php";

// Templates
$modversion['templates'] = array();
$modversion['templates'][count($modversion['templates'])+1]['file'] = 'radioo_playlist_asx.html';
$modversion['templates'][count($modversion['templates'])+0]['description'] = 'Media player playlist for ASX Format';
$modversion['templates'][count($modversion['templates'])+1]['file'] = 'radioo_playlist_b4s.html';
$modversion['templates'][count($modversion['templates'])+0]['description'] = 'Media player playlist for B4S Format';
$modversion['templates'][count($modversion['templates'])+1]['file'] = 'radioo_playlist_kapsule.html';
$modversion['templates'][count($modversion['templates'])+0]['description'] = 'Media player playlist for KAPSULE Format';
$modversion['templates'][count($modversion['templates'])+1]['file'] = 'radioo_playlist_kpl.html';
$modversion['templates'][count($modversion['templates'])+0]['description'] = 'Media player playlist for KPL Format';
$modversion['templates'][count($modversion['templates'])+1]['file'] = 'radioo_playlist_m3u.html';
$modversion['templates'][count($modversion['templates'])+0]['description'] = 'Media player playlist for M3U Format';
$modversion['templates'][count($modversion['templates'])+1]['file'] = 'radioo_playlist_magma.html';
$modversion['templates'][count($modversion['templates'])+0]['description'] = 'Media player playlist for MAGMA Format';
$modversion['templates'][count($modversion['templates'])+1]['file'] = 'radioo_playlist_pls.html';
$modversion['templates'][count($modversion['templates'])+0]['description'] = 'Media player playlist for PLS Format';
$modversion['templates'][count($modversion['templates'])+1]['file'] = 'radioo_playlist_ram.html';
$modversion['templates'][count($modversion['templates'])+0]['description'] = 'Media player playlist for RAM Format';
$modversion['templates'][count($modversion['templates'])+1]['file'] = 'radioo_playlist_rdf.html';
$modversion['templates'][count($modversion['templates'])+0]['description'] = 'Media player playlist for RDF Format';
$modversion['templates'][count($modversion['templates'])+1]['file'] = 'radioo_playlist_smil.html';
$modversion['templates'][count($modversion['templates'])+0]['description'] = 'Media player playlist for SMIL Format';
$modversion['templates'][count($modversion['templates'])+1]['file'] = 'radioo_playlist_xspf.html';
$modversion['templates'][count($modversion['templates'])+0]['description'] = 'Media player playlist for XSPF Format';
$modversion['templates'][count($modversion['templates'])+1]['file'] = 'radioo.php.html';
$modversion['templates'][count($modversion['templates'])+0]['description'] = 'Template for the Secure Salt file in data/ like Database Config';
$modversion['templates'][count($modversion['templates'])+1]['file'] = 'radioo_search_terms.html';
$modversion['templates'][count($modversion['templates'])+0]['description'] = 'Logged on Wrapper';

// Menu
$modversion['hasMain'] = 1;
$modversion['config'][] = array(
		'name' => 'htaccess',
		'title' => '_RADIOO_MI_HTACCESS',
		'description' => '_RADIOO_MI_HTACCESS_DESC',
		'formtype' => 'yesno',
		'valuetype' => 'int',
		'default' => false
);

$modversion['config'][] = array(
		'name' => 'htaccess_path',
		'title' => '_RADIOO_MI_HTACCESS_PATH',
		'description' => '_RADIOO_MI_HTACCESS_PATH_DESC',
		'formtype' => 'text',
		'valuetype' => 'text',
		'default' => 'radioo'
);

$modversion['config'][] = array(
		'name' => 'htaccess_extension',
		'title' => '_RADIOO_MI_HTACCESS_SUFFIX',
		'description' => '_RADIOO_MI_HTACCESS_SUFFIX_DESC',
		'formtype' => 'text',
		'valuetype' => 'text',
		'default' => '.html'
);

$modversion['config'][] = array(
		'name' => 'js_notclient',
		'title' => '_RADIOO_MI_JS_NOT_LOGGGEDIN',
		'description' => '_RADIOO_MI_JS_NOT_LOGGGEDIN_DESC',
		'formtype' => 'yesno',
		'valuetype' => 'int',
		'default' => false
);

$modversion['config'][] = array(
		'name' => 'js_client',
		'title' => '_RADIOO_MI_JS_LOGGGEDIN',
		'description' => '_RADIOO_MI_JS_LOGGGEDIN_DESC',
		'formtype' => 'yesno',
		'valuetype' => 'int',
		'default' => true
);

$modversion['config'][] = array(
		'name' => 'pls_notclient',
		'title' => '_RADIOO_MI_PLS_NOT_LOGGGEDIN',
		'description' => '_RADIOO_MI_PLS_NOT_LOGGGEDIN_DESC',
		'formtype' => 'yesno',
		'valuetype' => 'int',
		'default' => false
);

$modversion['config'][] = array(
		'name' => 'pls_client',
		'title' => '_RADIOO_MI_PLS_LOGGGEDIN',
		'description' => '_RADIOO_MI_PLS_LOGGGEDIN_DESC',
		'formtype' => 'yesno',
		'valuetype' => 'int',
		'default' => true
);

$modversion['config'][] = array(
		'name' => 'groups',
		'title' => '_RADIOO_MI_GROUPS',
		'description' => '_RADIOO_MI_GROUPS_DESC',
		'formtype' => 'group_multi',
		'valuetype' => 'array',
		'default' => array(XOOPS_USER_ADMIN, XOOPS_GROUP_ANONYMOUS, XOOPS_GROUP_USERS)
);

xoops_load('XoopsLists');

$modversion['config'][] = array(
		'name' => 'themes',
		'title' => '_RADIOO_MI_THEMES',
		'description' => '_RADIOO_MI_THEMES_DESC',
		'formtype' => 'theme_multi',
		'valuetype' => 'array',
		'default' => XoopsLists::getDirListAsArray(XOOPS_ROOT_PATH . DIRECTORY_SEPARATOR . 'themes')
);

$modversion['config'][] = array(
		'name' => 'banned_user',
		'title' => '_RADIOO_MI_BANNED_USER',
		'description' => '_RADIOO_MI_BANNED_USER_DESC',
		'formtype' => 'user_multi',
		'valuetype' => 'array',
		'default' => array(1=>1)
);

$modversion['config'][] = array(
		'name' => 'api_cache',
		'title' => '_RADIOO_MI_API_CACHE',
		'description' => '_RADIOO_MI_API_CACHE_DESC',
		'formtype' => 'select',
		'valuetype' => 'int',
		'options' => array(	_RADIOO_MI_15MINS => (15 * 60), _RADIOO_MI_30MINS => (30 * 60), _RADIOO_MI_1HOUR => (60 * 60), _RADIOO_MI_2HOURS => (120 * 60), 
							_RADIOO_MI_4HOURS => (240 * 60), _RADIOO_MI_8HOURS => (480 * 60),  _RADIOO_MI_16HOURS => (960 * 60), _RADIOO_MI_32HOURS => (1920 * 60),
							 _RADIOO_MI_64HOURS => (2840 * 60), _RADIOO_MI_1WEEK => (3600 * 24 * 7)),
		'default' => (30 * 60)
);

$modversion['config'][] = array(
		'name' => 'api_format',
		'title' => '_RADIOO_MI_API_FORMAT',
		'description' => '_RADIOO_MI_API_FORMAT_DESC',
		'formtype' => 'select',
		'valuetype' => 'text',
		'options' => array('json'=>'json', 'xml'=>'xml', 'serial'=>'serial'),
		'default' => 'json'
);

$modversion['config'][] = array(
		'name' => 'api_primarygenres',
		'title' => '_RADIOO_MI_PRIMARY_GENRES',
		'description' => '_RADIOO_MI_PRIMARY_GENRES_DESC',
		'formtype' => 'text',
		'valuetype' => 'text',
		'default' => 'http://life.labs.coop/v2/radio/genres/primary/json.api'
);


$modversion['config'][] = array(
		'name' => 'api_allgenres',
		'title' => '_RADIOO_MI_ALL_GENRES',
		'description' => '_RADIOO_MI_ALL_GENRES_DESC',
		'formtype' => 'text',
		'valuetype' => 'text',
		'default' => 'http://life.labs.coop/v2/radio/genres/all/json.api'
);

$modversion['config'][] = array(
		'name' => 'api_top500',
		'title' => '_RADIOO_MI_STATIONS_TOP500',
		'description' => '_RADIOO_MI_STATIONS_TOP500_DESC',
		'formtype' => 'text',
		'valuetype' => 'text',
		'default' => 'http://life.labs.coop/v2/radio/top500/json.api'
);

$modversion['config'][] = array(
		'name' => 'api_random',
		'title' => '_RADIOO_MI_STATION_RANDOM',
		'description' => '_RADIOO_MI_STATION_RANDOM_DESC',
		'formtype' => 'text',
		'valuetype' => 'text',
		'default' => 'http://life.labs.coop/v2/radio/random/json.api'
);

$modversion['config'][] = array(
		'name' => 'api_search',
		'title' => '_RADIOO_MI_STATIONS_SEARCH',
		'description' => '_RADIOO_MI_STATIONS_SEARCH_DESC',
		'formtype' => 'text',
		'valuetype' => 'text',
		'default' => 'http://life.labs.coop/v2/radio/search/%s/json.api'
);

$modversion['config'][] = array(
		'name' => 'api_search',
		'title' => '_RADIOO_MI_STATIONS_GENRE',
		'description' => '_RADIOO_MI_STATIONS_GENRE_DESC',
		'formtype' => 'text',
		'valuetype' => 'text',
		'default' => 'http://life.labs.coop/v2/radio/genre/%s/json.api'
);

$modversion['config'][] = array(
		'name' => 'api_streams',
		'title' => '_RADIOO_MI_STATION_STREAMS',
		'description' => '_RADIOO_MI_STATIONS_STREAMS_DESC',
		'formtype' => 'text',
		'valuetype' => 'text',
		'default' => 'http://life.labs.coop/v2/radio/station/%s/json.api'
);

$modversion['config'][] = array(
		'name' => 'identify_genre',
		'title' => '_RADIOO_MI_IDENTIFIER_GENRES',
		'description' => '_RADIOO_MI_IDENTIFIER_GENRES_DESC',
		'formtype' => 'text',
		'valuetype' => 'text',
		'default' => '%elementkey%'
);

$modversion['config'][] = array(
		'name' => 'identify_station',
		'title' => '_RADIOO_MI_IDENTIFIER_STATION_KEY',
		'description' => '_RADIOO_MI_IDENTIFIER_STATION_KEY_DESC',
		'formtype' => 'text',
		'valuetype' => 'text',
		'default' => 'key'
);

$modversion['config'][] = array(
		'name' => 'key_station_name',
		'title' => '_RADIOO_MI_KEYS_STATION_NAME',
		'description' => '_RADIOO_MI_KEYS_STATION_NAME_DESC',
		'formtype' => 'text',
		'valuetype' => 'text',
		'default' => 'name'
);

$modversion['config'][] = array(
		'name' => 'key_station_hears',
		'title' => '_RADIOO_MI_KEYS_STATION_LISTENERS',
		'description' => '_RADIOO_MI_KEYS_STATION_LISTENERS_DESC',
		'formtype' => 'text',
		'valuetype' => 'text',
		'default' => 'listeners'
);

$modversion['config'][] = array(
		'name' => 'key_station_current',
		'title' => '_RADIOO_MI_KEYS_STATION_CURRENT_TRACK',
		'description' => '_RADIOO_MI_KEYS_STATION_CURRENT_TRACK_DESC',
		'formtype' => 'text',
		'valuetype' => 'text',
		'default' => 'currenttrack'
);

$modversion['config'][] = array(
		'name' => 'key_station_bit',
		'title' => '_RADIOO_MI_KEYS_STATION_BITRATE',
		'description' => '_RADIOO_MI_KEYS_STATION_BITRATE_DESC',
		'formtype' => 'text',
		'valuetype' => 'text',
		'default' => 'currenttrack'
);

$modversion['config'][] = array(
		'name' => 'key_station_format',
		'title' => '_RADIOO_MI_KEYS_STATION_FORMAT',
		'description' => '_RADIOO_MI_KEYS_STATION_FORMAT_DESC',
		'formtype' => 'text',
		'valuetype' => 'text',
		'default' => 'format'
);
?>